### PR TITLE
Revert "move back to setuptools (#367)"

### LINKED ISSUE #340: Transition to using `flit`
> should we choose to something that uses `pyproject.toml` like flit?

_Originally posted by @brettcannon in https://github.com/pypa/packaging/pull/332#discussion_r504211139_

Yes. :)

### PR DESCRIPTION
**Pull request by vishwin**
Fixes #340, again

`flit_core` and `installer` are now mature enough to bootstrap themselves. Needed to enable a `setuptools`-free bootstrap environment and avoid circular dependencies.

This reverts commit 14ad3520dc866295963c677c6813646b8a59a6a6.

Signed-off-by: Charlie Li <vishwin@FreeBSD.org>

### CODE REVIEW

**Comment by brettcannon** [comment]
@pradyunsg should we accept this and do a separate port over to PEP 621? And where do you want the version to live: `__init__.py` or `pyproject.toml`?

**Comment by pradyunsg** [comment]
I'm fine with doing it in one shot or two. I have a mild preference for putting the version in `__init__.py` but don't feel strongly either way. :)

**Comment by brettcannon** [comment]
@vishwin would you mind addressing the linting errors?

**Comment by vishwin** [comment]
I'll try, and probably just PEP-621 it in the process

**Comment by brettcannon** [comment]
@rossburton I'm waiting to see if #546 goes anywhere before considering this PR.

**Comment by nanonyme** [comment]
@brettcannon seems #546 is reasonably mature at this point, pending final review. Probabaly worth focusing on that at this point.

**Comment by pradyunsg** [comment]
Given that #546 is approved and this one has merge conflicts, I'm gonna go ahead and close this out.

Thanks for filing this @vishwin! ^>^

**Pull request closed without merging**
