### PR TITLE
Correctly handle non-normalised specifiers in requirements

### LINKED ISSUE #629: 22.0: The new requirement parser doesn't handle unnormalized specifiers
```python
from packaging.specifiers import SpecifierSet
from packaging.requirements import Requirement

s = SpecifierSet('>=1.0-alpha')  # success
"1.0a0" in s  # True

r = Requirement('foo>=1.0-alpha')  # Error
```

Ideally, we should make them consistent.

### PR DESCRIPTION
**Pull request by pradyunsg**
Closes #629

### CODE REVIEW

**Comment by pradyunsg** [comment]
Actually, strictly speaking, [`f6fd2e6` (#634)](https://github.com/pypa/packaging/pull/634/commits/f6fd2e6f419248455a9ab1ae7ff25d4bfef45eda) is enough to fix #629.

**Review by brettcannon — APPROVED** [review]

**Comment by pradyunsg** [comment]
Thanks @brettcannon for the review! ^>^

**Comment by brettcannon** [comment]
> Thanks @brettcannon for the review! ^>^

Thank good timing that I happened to be going through my GitHub notifications right around when you published this PR. 😁

**Comment by frostming** [comment]
Verified, it fixed the issue.

**Pull request merged**
