### PR TITLE
Clean up and improve typing

### PR DESCRIPTION
**Pull request by jdufresne**
- Enable "warn_unused_ignores" in `mypy.ini`
- Replace internal `_typing` module with stdlib 
- Remove `TYPE_CHECKING` guards
- Move type comments to inline annotations

### CODE REVIEW

**Comment by brettcannon** [comment]
@jdufresne as thanks for your Python 2.7 removal PR, can you update this PR? 😉

**Comment by jdufresne** [comment]
Rebased :tada:

**Comment by pradyunsg** [comment]
I love how @jdufresne will have touched _nearly_ every single file in this repo after this change. :P

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
@jdufresne thanks!

**Comment by pradyunsg** [comment]
Indeed! Thanks @jdufresne! ^>^

**Pull request merged**
