### PR TITLE
CI: Add Python 3.11, update checkout to v3, weekly run

### PR DESCRIPTION
**Pull request by EwoutH**
A bit of maintenance on the CI:
- Add Python 3.11 (which is currently in beta) to the build matrix of the CI test job
- A weekly scheduled run is also added to catch changes in dependencies and environments (each Monday at 06:00 UTC), and workflow_dispatch is added to be able to manually trigger the CI workflow
- The checkout actions is updated to v3

### CODE REVIEW

**Comment by EwoutH** [comment]
Hi @brettcannon and @mayeut, would one of you be able to take a look at this PR?

**Review by brettcannon — CHANGES_REQUESTED** [review]
I'm afraid you will need to manipulate the `3.11-dev` string to be just `3.11` to pass into nox.

**Comment by brettcannon** [comment]
@EwoutH did you want to try and make this work? Or should I just go ahead and close the PR?

**Comment by henryiii** [comment]
Can't you just add a line like:

```
INTERPRETER=${INTERPRETER/-dev/}
```

Right before the similar line that just strips `-`?

**Comment by henryiii** [comment]
This should also add the 3.11 trove classier, though that will clash with the moves in #546.

**Pull request closed without merging**
