### PR TITLE
Fix test_linux_platforms_manylinux* on architectures other than x86_64

### PR DESCRIPTION
**Pull request by mbakke**
These patches allow the manylinux tests to pass on non-x86 by mocking the platform.  Tested on armv7, aarch64, i686, and x86_64 GNU/Linux.

### CODE REVIEW

**Comment by pradyunsg** [comment]
*sigh*

**Comment by mbakke** [comment]
I rebased the patches on the current master branch.

**Comment by brettcannon** [comment]
@mbakke it looks like your branch is out of date.

**Comment by mbakke** [comment]
@brettcannon thanks for the notice, I did another rebase.

**Comment by mbakke** [comment]
Was there anything else holding this PR?

**Comment by brettcannon** [comment]
@mbakke only thing missing is time; either from me to have it to do a review or @pradyunsg having it to merge this PR if he's still happy with it.

**Comment by pradyunsg** [comment]
I'm good with this PR. @brettcannon if you do come around to this PR and have concerns, do let me know! :)

**Pull request merged**
