### PR TITLE
move back to setuptools

### LINKED ISSUE #363: Reliance on flit makes packaging incompatible with Void, Arch and Alpine Linux package systems
The switch to `flit` in #352 has left the `packaging` source tarball without a `setup.py`. While one can use `flit install` to install `packaging`, the `flit install` command provides a means to choose between installing to the system `site-packages` (possibly in a virtualenv, by providing a custom path to the `python` executable) or to a per-user `site-packages`.

Void Linux `xbps-src`, Arch Build System and Alpine `apk-tools` package builders all expect to install Python packages into a specific destination directory that is empty except for the contents of the Python package; the distribution package is derived from the contents of this directory. For `setuptools`-based projects like `packaging<20.5`, this is accomplished by passing, *e.g.*, `--root $DESTDIR` for Void Linux. `flit install` provides no similar mechanism. The closest one could come would be to construct a virtualenv at the `$DESTDIR`, then use `flit install` to populate, and then carefully remove all pieces of the virtualenv from `$DESTDIR` except for the installed package. It should be self evident that this is a horrible workaround.

If you are use `flit build` and `flit publish` to build wheels and source tarballs on PyPI, this problem should take care of itself, because both `flit` subcommands appear to create a `setup.py` in the source tarball by default. (Note, however, that the generated `setup.py` appears incorrect because it imports `distutils.core.setup`, then uses the `install_requires` and `python_requires` keywords that seem to be only recognized by `setuptools.setup`.) However, the PyPI source tarballs for `packaging==20.5`, `packaging==20.6` and `packaging==20.7` do not include `setup.py`. Thus, you are either creating a source tarball by some other means, or invoking `flit build --no-setup-py` or `flit publish --no-setup-py`.

Without a `setup.py` in the source tarball (either generated by `flit build` or `flit publish`, or manually created to parallel the package definition in `pyproject.toml`), new versions of `packaging` cannot be properly packaged for Void, Arch, Alpine and, I imagine, several other Linux distributions.

### PR DESCRIPTION
**Pull request by FFY00**
Closes #363

Signed-off-by: Filipe Laíns <lains@riseup.net>

### CODE REVIEW

**Comment by uranusjr** [comment]
Does this only revert the PR that switched to Flit? Because this is not exactly what I’d expect if packaging switches to setuptools afresh in 2020.

**Comment by FFY00** [comment]
Basically yeah, only a few minor differences. I kept `mypy.ini`, to avoid dirtying the history further and ease the move to flit in the future, and explicitly specified the `setuptools.build_meta` backend in `pyproject.toml`.

It's not a clean revert because the same commit also switched to pypa/build and @brettcannon wanted to keep that.

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
It kept what I cared about, so I'm fine with taking the PR as-is. Thanks, @FFY00 !

**Comment by pradyunsg** [comment]
Who's cutting the release? ;)

https://github.com/pypa/packaging/blob/master/docs/development/release-process.rst

**Comment by brettcannon** [comment]
I can do it Friday if no one else has time before then.

**Comment by brettcannon** [comment]
Release 20.8 is out!

**Pull request merged**
