### PR TITLE
Replace spaces in platform names with underscores

### LINKED ISSUE #652: Spaces in platform names are problematic
On some platforms, `sysconfig.get_platform()` returns a value with a space in it (e.g. `isilon onefs`).
This causes problems for wheel building/handling.

First, there is an issue trying to build a platform-specific wheel:
``` console
# venv/bin/pip install -I --no-cache pyyaml
Collecting pyyaml
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 KB 13.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pyyaml
  Building wheel for pyyaml (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pyyaml (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [101 lines of output]
...
      wheel.cli.WheelError: Bad wheel filename 'PyYAML-6.0-cp38-cp38-isilon onefs_9_5_0_0_amd64.whl'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyyaml
```
I created https://github.com/pypa/wheel/pull/491 to address this.

Even with that patch in place, though, `pip` is unable to install the built wheel because `packaging` does not recognize that the platform name has had its spaces replaced with underscores:
``` console
# python3 -m pip install dist/PyYAML-6.0-cp38-cp38-isilon_onefs_9_5_0_0_amd64.whl
...
ERROR: PyYAML-6.0-cp38-cp38-isilon_onefs_9_5_0_0_amd64.whl is not a supported wheel on this platform.
```

### PR DESCRIPTION
**Pull request by tucked**
Resolve #652

### CODE REVIEW

**Review by brettcannon — CHANGES_REQUESTED** [review]
Please add tests.

**Comment by tucked** [comment]
@brettcannon done!

**Comment by brettcannon** [comment]
I just realized there's no issue associated with this PR, so folks don't know there's a decision to be made here.

@tucked would you mind creating an issue?

**Comment by brettcannon** [comment]
@tucked I'm ready to review this again, but I still need an issue to be created so I can discuss this with the other maintainer to make sure this isn't going to be a breaking change in some way that I can't think of.

**Comment by tucked** [comment]
Hey @brettcannon, thanks for getting back to me and sorry for the delay. I've been out for the holidays.

I've created https://github.com/pypa/packaging/issues/652 and linked this PR to it! I've also rebased this PR onto the latest `main`.

**Comment by tucked** [comment]
It looks like a new test was added recently which breaks with this change:
https://github.com/pypa/packaging/blob/206797003d9bf9c04d3db17c564d13eae9e4e54a/tests/test_tags.py#L845-L848
```
=================================== FAILURES ===================================
_____________________ TestGenericTags.test__generic_abi_jp _____________________

self = <tests.test_tags.TestGenericTags object at 0x7fc9ff9db050>
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7fc9fa175e10>

    def test__generic_abi_jp(self, monkeypatch):
        config = {"EXT_SUFFIX": ".return exactly this.so"}
        monkeypatch.setattr(sysconfig, "get_config_var", config.__getitem__)
>       assert tags._generic_abi() == ["return exactly this"]
E       AssertionError: assert ['return_exactly_this'] == ['return exactly this']
E         At index 0 diff: 'return_exactly_this' != 'return exactly this'
E         Full diff:
E         - ['return exactly this']
E         ?         ^       ^
E         + ['return_exactly_this']
E         ?         ^       ^

tests/test_tags.py:861: AssertionError
=========================== short test summary info ============================
FAILED tests/test_tags.py::TestGenericTags::test__generic_abi_jp - AssertionError: assert ['return_exactly_this'] == ['return exactly this']
  At index 0 diff: 'return_exactly_this' != 'return exactly this'
  Full diff:
  - ['return exactly this']
  ?         ^       ^
  + ['return_exactly_this']
  ?         ^       ^
======================= 1 failed, 26341 passed in 57.45s =======================
```
I suppose that suggests that we may only want to normalize spaces in `_generic_platforms` or maybe `platform_tags`:
https://github.com/pypa/packaging/blob/206797003d9bf9c04d3db17c564d13eae9e4e54a/src/packaging/tags.py#L483-L496

**Comment by brettcannon** [comment]
> I suppose that suggests that we may only want to normalize spaces in `_generic_platforms` or maybe `platform_tags`

Not necessarily. It's something we can discuss as to what's best to do.

**Comment by tucked** [comment]
> Not necessarily. It's something we can discuss as to what's best to do.

👌 Good to know.... I already made the adjustment from [the previous diff](https://github.com/pypa/packaging/commit/b9acbcc37c7db08f601cefe376796fa91ce60f45), but we can always switch back if that ends up being the best route.

**Comment by tucked** [comment]
Based on Matti's response in #652, I've switched back to the original diff and patched the new test.

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
@tucked Thanks!

**Pull request merged**
