### PR TITLE
Add `operator` and `version` properties to `Specifier`

### PR DESCRIPTION
**Pull request by nvie**
This adds the `operator` and `version` properties, to provide a public way of accessing the underpinnings of the Specifier (and LegacySpecifier) class.

In a nutshell:

```python
>>> s = Specifier('~=2.*')
>>> s.operator
'~='
>>> s.version
'2.*'
```

### CODE REVIEW

**Comment by dstufft** [comment]
Looks fine, though I do have one possible addition: Do you think it makes sense to also add a public attribute to ``SpecifierSet`` that lets you iterate over the underlying specifiers? Currently we don't have one because there's no public interface to a ``Specifier`` besides things like ``contains()`` and ``filter()`` which have an equivalent function on ``SpecifierSet`` so there wasn't a need to reach into the underlying ``Specifier`` instances, but with this PR they have something that people may wish to access.

Concretely: Perhaps this should include an ``SpecifierSet.__iter__()`` method so that people can access all of the underlying specifiers (since I generally consider ``SpecifierSet`` to be the thing most people should be creating).

**Comment by nvie** [comment]
Hey @dstufft, this is _exactly_ what I am working on next, indeed. I wanted to start with the smallest PR first, and see if you wanted to have it in there in the first place. This makes sense to me, and I'll implement it. Do you want me to add that to this PR, or open a new one after this is merged?

**Comment by nvie** [comment]
Okay, I've updated the SpecifierSet with the following Pythonic operators for iteration and membership testing: `__contains__`, `__len__` and `__iter__`.

**Comment by nvie** [comment]
Btw, one more question, what do you think `Specifier('==2.0').version` should return? Currently it returns the string `'2.0'`, but do you think it should return the result of `parse('2.0')` instead?

If so, we may have `version` return the parsed version, and `version_string` return the raw string value.

**Comment by nvie** [comment]
I went ahead and make it so `.version` returns a (parsed) `Version` instance. `.version_string` still allows access to the string, if needed.

**Comment by dstufft** [comment]
It should probably return a string, because it might not be a valid version, such as for ``==2.*``.

**Comment by nvie** [comment]
Ok, I've reverted that last commit, so `.version` is now just an interpreted string, as you suggested. Anything else you need for this to accept?

**Pull request closed without merging**
