### PR TITLE
Fix prerelease detection for `>` and `<`

### PR DESCRIPTION
**Pull request by notatallshaw**
Fixes https://github.com/pypa/packaging/issues/788

And adds an explicit test for `!=` based on https://github.com/pypa/packaging/issues/776#issuecomment-1900515985

### CODE REVIEW

**Comment by notatallshaw** [comment]
Feedback would be appreciated.

**Comment by uranusjr** [comment]
> And adds an explicit test for `!=`

Is this for another PR? I don’t see the change here.

**Comment by notatallshaw** [comment]
> > And adds an explicit test for `!=`
> 
> Is this for another PR? I don’t see the change here.

It's in the change to `tests/test_specifiers.py`

**Review by uranusjr — APPROVED** [review]

**Comment by notatallshaw** [comment]
I tried to merge branch with 'main' to make sure this PR was still good, but forgot I don't have automatic CI rights, if someone could approve CI run I'd be appreciative.

**Comment by notatallshaw** [comment]
Anything blocking this? Do I need to do anything for a changelog entry here?

**Review by brettcannon — CHANGES_REQUESTED** [review]
https://github.com/pypa/packaging/issues/788#issue-2209462892 has some examples. We probably should have some tests for those.

**Comment by notatallshaw** [comment]
> [#788 (comment)](https://github.com/pypa/packaging/issues/788#issue-2209462892) has some examples. We probably should have some tests for those.

Added specifier tests to match.

**Comment by notatallshaw** [comment]
The specifics of this came up today in https://github.com/astral-sh/uv/issues/6640

It reminded me to check this PR, it seems there was a transient CI error, I added some more tests, and after correcting them, the transient CI error vanished.

**Review by brettcannon — APPROVED** [review]

**Comment by brettcannon** [comment]
I'm going to give @pradyunsg a chance to (dis)agree to the semantic change before I merge.

**Review by pradyunsg — APPROVED** [review]

**Comment by brettcannon** [comment]
Thanks, @notatallshaw !

**Pull request merged**
