### PR TITLE
Updated security documentation as per PyPI security policy

### PR DESCRIPTION
**Pull request by snbk97**

### CODE REVIEW

**Comment by di** [comment]
Thanks @snbk97!

**Comment by brainwane** [comment]
Thank you @snbk97! If you would like a suggestion for another issue in https://github.com/pypa to fix, please reply and let us know!

**Comment by snbk97** [comment]
@brainwane Yes, definitely.

**Comment by brainwane** [comment]
@snbk97 I am so sorry for missing this reply back in July! Perhaps you'd like to try https://github.com/pypa/setuptools/issues/1698 ?

**Comment by snbk97** [comment]
I currently cannot work on anything as my laptop is not functioning
properly. I will be certain to checkout the repo for other issues, when it
gets fixed.

**Pull request merged**
