### PR TITLE
Clarify some release details

### PR DESCRIPTION
**Pull request by brettcannon**

### CODE REVIEW

**Review by pradyunsg — COMMENTED** [review]
Instead of opening the webbrowser, maybe we should make annotated tags instead?

**Comment by brettcannon** [comment]
Either or. Do annotated tags lead to a GitHub release? It also won't lead to the wheel and sdist being attached to the GitHub release.

**Comment by pradyunsg** [comment]
Hmm... Fair. It does lead to a release and I guess we can automate the rest later. :P

**Comment by brettcannon** [comment]
#339 covers that and I would actually make it a GHA that uses a [`workflow_dispatch` trigger](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch) so we can trigger from the browser, but otherwise does the entire release process (sans GPG signing) automatically.

**Comment by brettcannon** [comment]
So do you still want to switch to an annotated tag, or is this good enough until we automate more?

**Review by pradyunsg — APPROVED** [review]
Oh, I thought I'd already green ticked this. Whoops!

**Comment by brettcannon** [comment]
I will merge this once #376 is merged.

**Pull request merged**
