### PR TITLE
Added Version.bump_(major|minor|patch)

### PR DESCRIPTION
**Pull request by venthur**
These functions return a new Version instance with the appropriate
.release-part increased by one or raises a ValueError if that part does
not exist.

Closes: #114

### CODE REVIEW

**Comment by venthur** [comment]
The Travis CI failed due to a timeout and is unrelated to this PR:
```
3.4 is not installed; attempting download
Downloading archive: https://s3.amazonaws.com/travis-python-archives/binaries/ubuntu/14.04/x86_64/python-3.4.tar.bz2
$ curl -sSf -o python-3.4.tar.bz2 ${archive_url}
curl: (7) Failed to connect to s3.amazonaws.com port 443: Connection timed out
```
I cannot restart the job, I could do a dummy push to trigger a new run.

**Comment by venthur** [comment]
Refreshed the patch from master. Any updates on this?

**Comment by pradyunsg** [comment]
Hmm... I think this is better served as a part of a tool on top of packaging, like pypi.org/p/bump.

**Comment by venthur** [comment]
Hmpf, @pradyunsg You created the issue that this PR is trying to fix, and you gave an initial thumbs-up for the PR itself. Now you're just closing it. This seems a bit random and demotivating from my POV.

**Comment by pradyunsg** [comment]
Ah gee. Really sorry about that @venthur! 🙈 I didn't actually close it but I won't blame Brett here because it is my mess.

That issue was from a while back (and the thumbs up) and I've since had time to understand things around the packaging ecosystem better.

Relevant here, I realized that this package should only do implementation work for things that clearly don't have alternatives (like PEP defined things like versions).

Version bumping does have alternatives and there are various ways to handle them. Which is why, we shouldn't implement it in packaging. Since folks would take this to be the "official way" to do version bumping or take this as a signal that you should have major-minor-patch style versioning.

I'm sorry that I couldn't elaborate earlier -- I had an exam just now. I was planning to elaborate after it, which is well, now.

Thanks for clearly stating how you felt and I'm sorry about how things ended up. 🙈

**Comment by brettcannon** [comment]
I'll also link to my [blog post on the whole subject of open source contributions](https://snarky.ca/setting-expectations-for-open-source-participation/) (which based on a keynote if you prefer a video). Hopefully that can provide another viewpoint so that you don't feel demotivated when this happens again to you regardless of the project as chances are it will.

**Pull request closed without merging**
